# Generated by Django 4.2.2 on 2023-08-25 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendor', '0017_category_date_subcategory_date_alter_addproduct_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reciverName', models.CharField(max_length=50, null=True)),
                ('fullAddress', models.TextField()),
                ('landmark', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserSignUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_fname', models.CharField(max_length=30)),
                ('u_lname', models.CharField(max_length=30)),
                ('u_email', models.EmailField(max_length=50, unique=True)),
                ('u_password', models.TextField()),
                ('date', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50, null=True)),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor.addproduct')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userApi.usersignup')),
            ],
        ),
        migrations.CreateModel(
            name='PlaceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartAmount', models.IntegerField(null=True)),
                ('paymentId', models.IntegerField(null=True)),
                ('paymentMode', models.CharField(max_length=30, null=True)),
                ('trackingNo', models.IntegerField(null=True)),
                ('status', models.IntegerField(null=True)),
                ('date', models.CharField(max_length=50, null=True)),
                ('addressId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userApi.address')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userApi.usersignup')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(null=True)),
                ('orderPlacedStatus', models.BooleanField(default=0)),
                ('date', models.CharField(max_length=50, null=True)),
                ('placeOrderId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userApi.placeorder')),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor.addproduct')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userApi.usersignup')),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userApi.usersignup'),
        ),
    ]
