# Generated by Django 4.2.2 on 2023-07-02 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserSignUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_fname', models.CharField(max_length=30)),
                ('u_lname', models.CharField(max_length=30)),
                ('u_email', models.CharField(max_length=50)),
                ('u_password', models.TextField()),
            ],
        ),
    ]
