# Generated by Django 4.2.2 on 2023-07-11 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userApi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productId', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('venId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userApi.usersignup')),
            ],
        ),
    ]
