# Generated by Django 4.2.2 on 2023-08-25 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApi', '0002_alter_placeorder_addressid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placeorder',
            name='status',
        ),
        migrations.AddField(
            model_name='placeorder',
            name='orderPlacedStatus',
            field=models.BooleanField(default=0),
        ),
    ]
