# Generated by Django 4.2.2 on 2023-08-25 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userApi', '0003_remove_placeorder_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='placeorder',
            old_name='orderPlacedStatus',
            new_name='status',
        ),
    ]
