# Generated by Django 4.2.2 on 2023-07-12 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0008_delete_cart'),
        ('userApi', '0004_cart_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='productId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor.addproduct'),
        ),
    ]
