# Generated by Django 4.2.2 on 2023-07-13 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0008_delete_cart'),
        ('userApi', '0005_alter_cart_productid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='productId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relateds', to='vendor.addproduct'),
        ),
    ]
