# Generated by Django 4.2.2 on 2023-07-14 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApi', '0009_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='reciverName',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
