# Generated by Django 4.2.2 on 2023-07-18 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApi', '0012_remove_placeorder_productid_remove_placeorder_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='orderPlacedStatus',
            field=models.BooleanField(default=0),
        ),
    ]
